### PR TITLE
feat: setup node api based on Redux store

### PR DESCRIPTION
**Pull request by EvanLovely**
To see it working and to play around with it:

```bash
cd examples/bootstrap
# Edit the below file to try different stuff
node ./node-api-example.js
```

Typescript auto-completion should contain all the docs you need, so make sure you build it all first:

```bash
yarn
yarn build
yarn build:types
```

### CODE REVIEW

**Review by sghoweri — COMMENTED** [review]
@EvanLovely just a couple bits of initial feedback after starting to kick the tires on this but very nice work overall -- super exciting to see this come together and start to bridge things together!

1. If I run that standalone node script while serving up the Bootstrap demo, the data in the filesystem updates however the browser doesn't refresh or immediately update to reflect the changes (ie no redux actions from a browser POV) until I manually refresh my browser... and yes I totally understand why that is currently -- Is there anything we can do about that?

2. We realllllllly need to make sure we do something to ensure ids are unique. Preferably we handle that internally vs require customers to have to manage that. Could be something we tackle separately but I'm weary about having something like that (public API) be floating around out there without a solid strategy.

While testing this out, I ended up creating two extra Button pages which not only matched up with my existing button page (all three highlighted when active) but when I went to delete the duplicate(s) from the nav, all 3 got removed 🤦 

3. How the heck do I use this awesome Node API with a plugin?

If I call the `start()` + `finish()` methods in-between performing an action (ex. add 1 new page) in the `init()` method of a test plugin, I get into an infinite loop. Ok... so probably running into issues because the brain is already booted up?

Also tested: if I _don't_ call the `start()` + `finish()` methods in my test plugin, nothing happens.

Also also tested: don't call `start()` and only try calling `finish()` which also doesn't work (throws the error about you need to call start first). 

4. Would love to figure out how to get rid of requiring the start and finish methods, however that's really not a deal-breaker for me. Heck, I'd even be fine holding off till the next big iteration of our API before coming up with a solution (ie. major breaking change)

5. We _really_ need to make sure the redux cleanup work is on Lisa's radar. If it's not tracked, assume it doesn't exist and it isn't going to have time allocated to work on it.

**Comment by EvanLovely** [comment]
On my phone so can't respond fully now, but could you elaborate on 2? Which IDs?

**Comment by sghoweri** [comment]
No worries (on my phone too) - I can go into more detail tomorrow but TLDR: because there's already a button component with an ID of `button` in your example here, the Bootstrap demo then had two Nav Items (and I'm assuming component pages) with the same button ID: https://github.com/basaltinc/knapsack/pull/564/files#diff-3d638da623df647fcdd92c643c16f4a0R12

**Comment by EvanLovely** [comment]
@sghoweri All changes we've discussed have been added to this PR

**Comment by sghoweri** [comment]
> @sghoweri All changes we've discussed have been added to this PR

Thanks @EvanLovely! Let's get this shipped!

**Review by sghoweri — APPROVED** [review]

**Pull request merged**
