### PR TITLE
Fix: Update Card Demo Form Field Order

### PR DESCRIPTION
**Pull request by sghoweri**
Temp fix to manually update the order of form fields displayed until https://linear.app/knapsack/issue/KSP-262/display-typescript-props-as-documented-instead-of-alphabetizing is completed.

image

Tagging @brandonreid and @EvanLovely for this super quick review so we can get this merged down to `next` (whoever can check this out first) 😉

### CODE REVIEW

**Comment by EvanLovely** [comment]
@sghoweri you sure this PR shouldn't be here? https://github.com/knapsack-cloud/ks-demo-bootstrap

**Comment by sghoweri** [comment]
> @sghoweri you sure this PR shouldn't be here? https://github.com/knapsack-cloud/ks-demo-bootstrap

@EvanLovely yes, I'm sure. This is for the Nike demo which we haven't migrated over yet. Also, the new codebase isn't yet being used for customer demos (hence why I'm PRing it here).

**Comment by EvanLovely** [comment]
K, in it goes!

**Comment by sghoweri** [comment]
Thanks!

**Pull request merged**
